language: php
php:
  - '7.1'
  - hhvm
  - nightly

before_install: echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer self-update
  - travis_retry composer --version
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - php bin/phpunit